# Generated by Django 5.0.6 on 2024-07-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_rating_options_alter_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='active_update_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
