# Generated by Django 5.0.6 on 2024-07-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rating_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
